<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class container23bf17050c8ba7d31779e6be7b323636 extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Bmd\\NavBlockEnhancements\\Services\\FilePathResolver' => 'get1',
  'subEntry1' => 'get2',
  'Bmd\\NavBlockEnhancements\\Services\\UrlResolver' => 'get3',
  'subEntry2' => 'get4',
  'Bmd\\NavBlockEnhancements\\Providers\\AssetLoader' => 'get5',
  'subEntry3' => 'get6',
  'subEntry4' => 'get7',
  'Bmd\\NavBlockEnhancements\\Processors\\DropDown' => 'get8',
  'Bmd\\NavBlockEnhancements\\Processors\\Colors' => 'get9',
  'Bmd\\NavBlockEnhancements\\Processors\\Modal' => 'get10',
  'config.url' => 'get11',
  'config.path' => 'get12',
  'config.cache' => 'get13',
);

    protected function get2()
    {
        return $this->delegateContainer->get('config.path');
    }

    protected function get1()
    {
        $object = new Bmd\NavBlockEnhancements\Services\FilePathResolver($this->get2());
        return $object;
    }

    protected function get4()
    {
        return $this->delegateContainer->get('config.url');
    }

    protected function get3()
    {
        $object = new Bmd\NavBlockEnhancements\Services\UrlResolver($this->get4());
        return $object;
    }

    protected function get6()
    {
        return $this->delegateContainer->get('Bmd\\NavBlockEnhancements\\Services\\UrlResolver');
    }

    protected function get7()
    {
        return $this->delegateContainer->get('Bmd\\NavBlockEnhancements\\Services\\FilePathResolver');
    }

    protected function get5()
    {
        $object = new Bmd\NavBlockEnhancements\Providers\AssetLoader($this->get6(), $this->get7());
        return $object;
    }

    protected function get8()
    {
        $object = new Bmd\NavBlockEnhancements\Processors\DropDown();
        return $object;
    }

    protected function get9()
    {
        $object = new Bmd\NavBlockEnhancements\Processors\Colors();
        return $object;
    }

    protected function get10()
    {
        $object = new Bmd\NavBlockEnhancements\Processors\Modal();
        return $object;
    }

    protected function get11()
    {
        return 'http://localhost:8888/wp-content/plugins/navigation-block-enhancements/';
    }

    protected function get12()
    {
        return '/var/www/html/wp-content/plugins/navigation-block-enhancements/';
    }

    protected function get13()
    {
        return true;
    }

}
