<?php
/**
 * Script asset loader service.
 *
 * @package Bmd\NavBlockEnhancements
 * @author  Bob Moore <bob@bobmoore.dev>
 * @license GPL-2.0-or-later https://www.gnu.org/licenses/gpl-2.0.html
 * @link    https://github.com/bob-moore/Navigation-Block-Enhancements
 */

namespace Bmd\NavBlockEnhancements\Services;

/**
 * Handles registration and enqueueing of JavaScript files.
 *
 * Reads companion .asset.php files generated by wp-scripts to pull in
 * dependency lists and content-hash versions automatically. Uses the
 * injected resolvers so the package works as both a standalone plugin
 * and a composer dependency inside a theme.
 */
class ScriptLoader extends AssetLoader
{
	/**
	 * Register a script, auto-resolving dependencies and version from the
	 * companion .asset.php when the source is a local file.
	 *
	 * @param string            $handle       Script handle.
	 * @param string            $src          Relative path or full URL.
	 * @param array<int,string> $dependencies Additional dependencies.
	 * @param string|null       $version      Version override.
	 * @param array|bool        $args         wp_register_script args (in_footer etc.).
	 *
	 * @return bool
	 */
	public function register(
		string $handle,
		string $src = '',
		array $dependencies = [],
		string|null $version = null,
		array|bool $args = true
	): bool {
		$file = $this->path_resolver->resolve( $src );

		if ( is_file( $file ) && ! filesize( $file ) ) {
			return false;
		}

		if ( is_file( $file ) ) {
			$assets       = $this->getAssetData( str_replace( '.js', '', basename( $src ) ) );
			$dependencies = $assets['dependencies'];
			$version      = ! empty( $assets['version'] ) ? $assets['version'] : filemtime( $file );
			$src          = $this->url_resolver->resolve( $src );
		}

		return wp_register_script(
			handle: $handle,
			src: $src,
			deps: apply_filters( "{$this->package}_script_dependencies_{$handle}", $dependencies ),
			ver: $version,
			args: $args
		);
	}

	/**
	 * Register and enqueue a script.
	 *
	 * @param string                 $handle       Script handle.
	 * @param string                 $src          Relative path or full URL.
	 * @param array<int,string>|null $dependencies Additional dependencies.
	 * @param string|null            $version      Version override.
	 * @param array|bool|null        $args         wp_register_script args.
	 *
	 * @return bool
	 */
	public function enqueue(
		string $handle,
		string $src = '',
		?array $dependencies = [],
		?string $version = null,
		null|array|bool $args = true
	): bool {
		$registered = $this->register( $handle, $src, $dependencies ?? [], $version, $args ?? true );

		if ( ! $registered ) {
			return false;
		}

		wp_enqueue_script( handle: $handle );

		return true;
	}
}
